# Generated by Django 6.0.3 on 2026-05-14 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('completada', models.BooleanField(default=False, help_text='¿La tarea está completada?', verbose_name='Finalización de la tarea')),
                ('fecha_completado', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, help_text='Verdadero si NO está archivado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='card_image/')),
                ('etiqueta', models.ManyToManyField(blank=True, default=None, related_name='etiquetas', to='todolist.etiqueta')),
                ('responsable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea de proyecto',
                'verbose_name_plural': 'Tareas de los proyectos',
                'ordering': ['-id'],
            },
        ),
    ]
